// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })
// import '../assets/lib/owlcarousel/assets/owl.carousel.min.css';
// import '../assets/css/bootstrap.min.css';
// import '../assets/css/style.css';
import '/public/assets/lib/owlcarousel/assets/owl.carousel.min.css';
import '/public/assets/css/style.css';
import '/public/assets/css/bootstrap.min.css';
import { Providers } from "./redux/provider"
export const metadata = {
  title: 'Adept Booking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <meta content="" name="keywords" />
        <meta content="" name="description" />
        <link href="img/favicon.ico" rel="icon" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet" />

        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
{/* 
        <link href="/assets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />

        <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />

        <link href="/assets/css/style.css" rel="stylesheet" /> */}

      </head>
      <body >
      <Providers>
        {children}
      </Providers>


        <script src="https://code.jquery.com/jquery-3.4.1.min.js"  defer />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"  defer />
        <script src="../assets/lib/wow/wow.min.js"  defer />
        <script src="../assets/lib/easing/easing.min.js"  defer />
        <script src="../assets/lib/waypoints/waypoints.min.js"  defer />
        <script src="../assets/lib/owlcarousel/owl.carousel.min.js"  defer />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"  defer />
        <script src="../assets/js/main.js"  defer />

        {/* if enything give error use async in script tag for JQuery */}
        
      </body>

    </html>
  )
}
